### ISSUE TITLE
Elemental binders stop work since 5.5.5 version

### ISSUE THREAD

**Issue by uhloin** [Sirttas/ElementalCraft#127]
**Describe the bug**
Elemental binders (at least air and water) stop work in versions 5.5.5 and 5.5.6.

**To Reproduce**
Install version 5.5.6 of mod.
Place Element Container (medium) with air element. Place Element Binder. Put swift alloy receipt (gold, drenched ingot, copper, redstone, air crystal). Reaction does not start. Downgrade to version 5.5.4 (also downgrade Forge to 43.2.0). Restart Minecraft. Reaction starts.

Buggy version:
elementalcraft-1.19.2-5.5.6.jar
forge-1.19.2-43.2.3-installer.jar 
Valid version:
elementalcraft-1.19.2-5.5.4.jar 
forge-1.19.2-43.2.0-installer.jar

**Comment by Sirttas** [comment]
Fixed in 5.5.7

**Comment by alcheya** [comment]
This is still not working.. I updated and binder won't function. 5.5.7

**Comment by uhloin** [comment]
It's fixed for me. Alcheya do you update Forge?

**Comment by alcheya** [comment]
> 
Forge is release (recommended), 43.2.3

**Comment by Sirttas** [comment]
Fixed again in 5.5.8

**Comment by MunkeeJuice** [comment]
Has this bug resurfaced in 5.510 ?

I am currently playing ATM8 1.0.15 which is using Forge 43.2.6 and the element binder is not working, same issue as stated by others for earlier version.

**Comment by Sirttas** [comment]
@MunkeeJuice  Is the problem occurring for every recipe or just a specific one?

**Comment by MunkeeJuice** [comment]
The swift alloy ingot from what i can see.  Not tried any of the others, just going through the progression and hit the problem, so googled it and came across this, github issue with ppl experiencing the same issue as me on prev versions

**Comment by Sirttas** [comment]
It should be correctly working now and have been for a few version, check your setup, are you placing items in the correct order?

**Comment by MunkeeJuice** [comment]
@Sirttas i must have been doing something wrong, its working as expected now.  I logged off the server i was playing on, did exactly the same in a creative test world and it worked, logged back onto the server tried it again and it worked.  I can't have been placing them in the correct order but i double and tripled checked that before leaving this comment.  Sorry for wasting your time.
