### ISSUE TITLE
[1.18-Forge] Can't load into worlds if Elemental Craft + Silent Gear are loaded together.

### ISSUE THREAD

**Issue by Gbergz** [Sirttas/ElementalCraft#66]
## Versions
- **ElementalCraft**: 4.0.1
- **DataPack Anvil (Lib)**: 3.0.0b
- **Silent Gear**: 2.8.0
- **Silent Lib**: 6.0.0
- **Forge** 38.0.14
- **Optifine Installed**: No

## Expected Behavior
That the world loads when Elemental Craft & Silent Gear are both loaded together.

## Actual Behavior
Worlds fail to load and give out the disconnect message: "Server sent an invalid packet".

## Logs/Images
Logs: https://gist.github.com/Gbergz/91049273d23d1b5f48d7c8cb53a03ed7

Image:
![image](https://user-images.githubusercontent.com/26634554/144833743-23281f28-934d-4bc9-9dae-fa8b37db6bd6.png)

## Steps to Reproduce the Problem
1. Install ElementalCraft +DataPack Anvil (Lib)
2. Install Silent Gear + Lib
3. Load Game.
4. Create world.
5. Fail, error.
6. Profit.

**Reported this issue here aswell:**
https://github.com/SilentChaos512/Silent-Gear/issues/450

**-** Gbergz

**Comment by Sirttas** [comment]
I published a quick fix in 4.0.2, I hadn't the occasion to test it though.

**Comment by Gbergz** [comment]
Alright thanks.
I'll try it when its available

**Comment by Gbergz** [comment]
The error still happens with the new version.

edit:
Debug.log:
https://gist.github.com/Gbergz/a54d11d41dfc0fcdbcefab3e1deb3ffd

normal log:
https://gist.github.com/Gbergz/8dd7711d452989be3dc0c1784c0284ba

**Comment by Sirttas** [comment]
ok thanks, I'll take a look when I get home.

**Comment by ClaudiusMinimus** [comment]
I am having the same issue. I'm in the process of porting one of my packs to 1.18 and I get the exact error on screen as shown above. I can run either Elemental Craft or Silent Gear individually, but not together. I am running the latest versions.

[latest.log](https://github.com/Sirttas/ElementalCraft/files/7678607/latest.log)

[debug.log](https://github.com/Sirttas/ElementalCraft/files/7678608/debug.log)

![elementalcraft2021-12-08_12-43](https://user-images.githubusercontent.com/17887664/145276648-277b177f-72f3-4444-8db2-e1019e80dd6c.png)

I also found this log file
[hs_err_pid29262.log](https://github.com/Sirttas/ElementalCraft/files/7678621/hs_err_pid29262.log)

**Comment by oliverrook** [comment]
I can confirm deleting the silent gear material folders from the mod does fix the issue, though obviously gets rid of the cross compatability.

**Comment by Sirttas** [comment]
it should be fixed in 4.0.4

**Comment by ClaudiusMinimus** [comment]
Thank you for taking a look at this issue. I'll let you know if it happens
again.
Thanks again!
CM
PS: I love your mod and feel it will be a great addition to my pack!

**Comment by Gbergz** [comment]
tried 4.0.4, got a different error now with just ElementalCraft + DP.
logs:
https://gist.github.com/Gbergz/5788d8dd46036eb8d027696f0ec34ed7
debug:
https://gist.github.com/Gbergz/f9dcddde78354e2c173058a7963d4394

**Comment by Sirttas** [comment]
Thanks, I'll test and fix when I get home, I'll archive 4.0.4

**Comment by Gbergz** [comment]
Hey, any progress? :)

**Comment by Sirttas** [comment]
I had a busy week. I hope I get it done in a couple of weeks.

**Comment by Gbergz** [comment]
Gotcha, thanks. :)

**Comment by Sirttas** [comment]
should be fix in 4.1.0, also sg fixed something on their side
